/**
*
*
* \author Titouan Gaborit
* \date 26 avril 2019
*
*
*/

#ifndef CATANE_CONTROLLER_PLACE_URB_BUTTONS_H
#define CATANE_CONTROLLER_PLACE_URB_BUTTONS_H

#endif //CATANE_CONTROLLER_PLACE_URB_BUTTONS_H
